/**
 * The card catalog.
 *
 * There is deliberately no bundled catalog here. Templates live in Firestore
 * (`templates/{id}`) and are read through `CatalogContext`; this module is the
 * small in-memory mirror that the rest of the app queries, so pages can keep
 * using plain functions instead of threading the catalog through props.
 *
 * A previous version generated ~340 templates in this file (archetypes + an SVG
 * thumbnail generator) and shipped them in the JS bundle. That data is gone:
 *  - the running app now depends on the database, so the storefront reflects
 *    admin edits and deletions immediately;
 *  - build-time needs (prerendered card pages, cover-art check) read
 *    `scripts/catalog.manifest.json` instead, regenerated by
 *    `node scripts/export-manifest.mjs`.
 *
 * Do NOT add template data back here. See AGENTS.md.
 */

import { CardTemplate, OccasionType, RecipientType } from '../types/template';
import {
  saveCustomUploadedTemplate,
  deleteCustomUploadedTemplate,
} from '../utils/occasionTemplateLoader';

/**
 * Whatever Firestore last told us, plus any templates created in Occasion
 * Studio on this device. Starts empty: until the catalog is loaded (or a card
 * is created locally) there is nothing to show.
 */
let liveCatalog: CardTemplate[] = [];

/** Replace the live catalog (called by CatalogProvider on every snapshot). */
export function setLiveCatalog(templates: CardTemplate[]): void {
  liveCatalog = templates;
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('cardly_templates_updated'));
  }
}

/** The catalog the running app should read from. Never mutate the result. */
export function getLiveCatalog(): CardTemplate[] {
  return liveCatalog;
}

export function getTemplateById(id: string): CardTemplate | undefined {
  return liveCatalog.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: OccasionType): CardTemplate[] {
  return liveCatalog.filter((t) => t.category.toLowerCase() === category.toLowerCase());
}

export function getTemplatesByRecipient(recipient: RecipientType): CardTemplate[] {
  // `recipients` is an array, so a card for a "Friend" is also returned for
  // "Best Friend" when it lists both.
  return liveCatalog.filter((t) =>
    t.recipients.some((r) => r.toLowerCase() === recipient.toLowerCase())
  );
}

export function getPopularTemplates(limit = 12): CardTemplate[] {
  return liveCatalog.filter((t) => t.isPopular || t.isBestSeller).slice(0, limit);
}

export function getPhotoTemplates(limit = 12): CardTemplate[] {
  return liveCatalog.filter((t) => t.isPhotoCard).slice(0, limit);
}

/**
 * Occasion Studio's create/update path. Persists to this device only — the
 * catalog is no longer hardcoded, so a card created here is local until it is
 * written to Firestore by an admin.
 */
export function registerCustomTemplate(template: CardTemplate): void {
  saveCustomUploadedTemplate(template);
  const next = liveCatalog.filter((t) => t.id !== template.id);
  next.unshift(template);
  setLiveCatalog(next);
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('cardly_templates_updated', { detail: template }));
  }
}

export function unregisterCustomTemplate(templateId: string): void {
  deleteCustomUploadedTemplate(templateId);
  setLiveCatalog(liveCatalog.filter((t) => t.id !== templateId));
  if (typeof window !== 'undefined') {
    window.dispatchEvent(
      new CustomEvent('cardly_templates_updated', { detail: { id: templateId, deleted: true } })
    );
  }
}
